name: cmake package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package
      run: |
         cd build
         cpack -G DEB
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: xsetwacomgui-${{ github.ref_name:1 }}_amd64.deb
        path: _packages/xsetwacomgui_*_amd64.deb

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: _packages/xsetwacomgui_*_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
