name: cmake build release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Git
      run: |
        sudo apt update
        sudo apt install -y git
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Install Packages
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake ninja-build libfreetype6-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libudev-dev wget software-properties-common

    - name: Prepare Clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 20

    - name: Prepare AppImage Tools
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage

    - name: Build
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
        cmake --preset release -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20 -DCPACK_PACKAGE_VERSION=$VERSION
        cmake --build build

    - name: Build Packages
      run: |
        ls -l
        ./linuxdeployqt-continuous-x86_64.AppImage build/release/xsetwacomgui

    # - name: Upload
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: 
    #     path: _packages/xsetwacomgui_*_amd64.deb
    #
    # - name: Upload Build Tree
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: build-tree
    #     path: build

  # release:
  #   needs: build
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     contents: write
  #
  #   steps:
  #   - name: Download Build Tree
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: build-tree
  #       path: build
  #
  #   - name: Release
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: |
  #         _packages/xsetwacomgui_*_amd64.deb
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
