name: cmake build

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Deps
      run: |
         sudo apt update
         sudo apt install libfreetype6-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libudev-dev
    
    - name: Configure
      run: cmake --preset release

    - name: Build
      run: cmake --build build
